# Generated by Django 4.2.3 on 2024-07-25 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Publisher'), (3, 'Advertiser')], default=2, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, null=True)),
                ('vertical', models.CharField(choices=[('Apple', 'Apple'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Business', 'Business'), ('California', 'California'), ('Career', 'Career'), ('Computers', 'Computers'), ('Crypto', 'Crypto'), ('Deals', 'Deals'), ('Dye', 'Dye'), ('Family', 'Family'), ('Finance', 'Finance'), ('Food', 'Food')], max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email_list_size', models.IntegerField(null=True)),
                ('gender_split', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_ad_units', models.IntegerField(blank=True, null=True)),
                ('headline_copy_length', models.CharField(blank=True, max_length=300, null=True)),
                ('body_copy_length', models.CharField(blank=True, max_length=300, null=True)),
                ('accepts_cbd', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Neither', 'Neither'), ('Both', 'Both'), ('CBD Products only', 'CBD Products only'), ('Depends on Brand', 'Depends on Brand')], max_length=100, null=True)),
                ('cta_copy_length', models.CharField(blank=True, max_length=300, null=True)),
                ('editorial_copy_length', models.CharField(blank=True, max_length=300, null=True)),
                ('days_in_advance', models.IntegerField(blank=True, null=True)),
                ('average_age', models.IntegerField(blank=True, null=True)),
                ('hhi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('audience_geo', models.CharField(max_length=255, null=True)),
                ('mobile_vs_desktop', models.CharField(blank=True, max_length=255, null=True)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_level', models.CharField(blank=True, max_length=100, null=True)),
                ('media_kit', models.FileField(blank=True, null=True, upload_to='publisher/files')),
                ('files', models.FileField(blank=True, null=True, upload_to='publisher/files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, null=True, upload_to='profile/dp')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='profile/cover')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_types', models.CharField(choices=[('Banner', 'Banner'), ('Newsletter Inclusion', 'Newsletter Inclusion'), ('Editorial', 'Editorial'), ('Podcast', 'Podcast'), ('FInance', 'FInance'), ('Makegood', 'Makegood'), ('Email', 'Email'), ('Native', 'Native'), ('OP Type', 'OP Type'), ('New', 'New'), ('CPL', 'CPL'), ('Push', 'Push')], max_length=255, null=True)),
                ('email_service_provider', models.CharField(max_length=255, null=True)),
                ('open_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('CTR', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('expected_clicks', models.IntegerField(null=True)),
                ('logo_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A'), ('Optional', 'Optional'), ('Transparent 600 * 300', 'Transparent 600 * 300'), ('Yes(w/solid color and white bg)', 'Yes(w/solid color and white bg)')], max_length=100, null=True)),
                ('image_size', models.CharField(max_length=255, null=True)),
                ('number_of_placements', models.IntegerField(null=True)),
                ('placement_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nvoicing_contact', models.CharField(max_length=50, null=True)),
                ('invoicing_email', models.EmailField(max_length=254, null=True)),
                ('invoice_mailing_address', models.CharField(max_length=250, null=True)),
                ('primary_contact', models.CharField(max_length=50, null=True)),
                ('additional_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_disclaimer', models.TextField(blank=True, null=True)),
                ('promo_code', models.CharField(max_length=50, null=True)),
                ('value_propositoins', models.CharField(max_length=50, null=True)),
                ('apart_competitors', models.CharField(max_length=250)),
                ('focus_product', models.CharField(max_length=250, null=True)),
                ('barrier_purchase', models.CharField(max_length=250, null=True)),
                ('not_mention', models.CharField(max_length=250)),
                ('success_msg', models.CharField(max_length=250)),
                ('high_reslution_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='advertiser/logo')),
                ('files', models.FileField(blank=True, null=True, upload_to='advertiser/files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=150)),
                ('ad_title', models.CharField(max_length=150)),
                ('landing_page', models.CharField(max_length=50, null=True)),
                ('utm_structure', models.CharField(max_length=50, null=True)),
                ('target_matrics', models.CharField(max_length=250, null=True)),
                ('utm_parameters', models.CharField(max_length=50, null=True)),
                ('placement_types', models.CharField(choices=[('Banner', 'Banner'), ('Newsletter Inclusion', 'Newsletter Inclusion'), ('Editorial', 'Editorial'), ('Podcast', 'Podcast'), ('FInance', 'FInance'), ('Makegood', 'Makegood'), ('Email', 'Email'), ('Native', 'Native'), ('OP Type', 'OP Type'), ('New', 'New'), ('CPL', 'CPL'), ('Push', 'Push')], max_length=255, null=True)),
                ('target_market', models.CharField(max_length=150, null=True)),
                ('daily_budget', models.IntegerField(null=True)),
                ('total_budget', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('ad_goal', models.CharField(choices=[('Click', 'Click'), ('Conversion', 'Conversion'), ('Checkout', 'Checkout'), ('Engagement', 'Engagement')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
