# Generated by Django 4.2.3 on 2024-07-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertiser',
            old_name='nvoicing_contact',
            new_name='invoicing_contact',
        ),
    ]
