# Generated by Django 4.2.3 on 2024-07-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figmapp', '0002_rename_nvoicing_contact_advertiser_invoicing_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figmapp.ads')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figmapp.placement')),
            ],
        ),
    ]
