# Generated by Django 4.2.3 on 2024-07-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figmapp', '0003_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
