# Generated by Django 4.2.3 on 2024-07-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figmapp', '0004_ads_available_placement_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots', models.ImageField(null=True, upload_to='campaign/shots')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figmapp.campaign')),
            ],
        ),
    ]
