# Generated by Django 4.2.3 on 2024-07-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figmapp', '0005_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='ad/images')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figmapp.ads')),
            ],
        ),
    ]
