# Generated by Django 4.2.3 on 2024-07-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figmapp', '0006_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
